---
- name: check if user on slave exist
  mysql_user:
    name: wp_user
    host: 52.157.176.65
    password: erty
    priv: "*.*:REPLICATION SLAVE,REPLICATION CLIENT"
    state: present
  when:
    - mysql_replication_role == 'master'

- name: Vérifier l'état de la réplication sur Slave
  mysql_replication:
    mode: getslave
    login_user: wp_user
    login_password: erty
  ignore_errors: true
  register: slave
  when:
    - mysql_replication_role == 'slave'

- name: Vérifier l'état de la réplication sur Master
  mysql_replication: mode=getmaster
  delegate_to: bdd1
  register: master
  when:
    - mysql_replication_role == 'slave'

#Test de debug
#- debug:
#    msg: "{{ master }}"

- name: Configurer la replication sur le slave
  mysql_replication:
    mode: changemaster
    master_host: 52.157.176.65
    master_user: wp_user
    master_password: erty
    master_log_file: "{{ master.File }}"
    master_log_pos: "{{ master.Position }}"
  ignore_errors: true
  when:
    - mysql_replication_role == 'slave'

- name: Start replication
  mysql_replication: 
    mode: startslave
  when:
    - mysql_replication_role == 'slave'
