- name: start apache2
  service:
   name: apache2
   state: started

- name: enable apache2
  service:
   name: apache2
   enabled: yes

- name: reload apache
  service: 
   name: apache2 
   state: reloaded

