- name: install and start mysql
  apt:
   name: mysql-server
   update-cache: yes
  notify:
   - enable mysql
   - start mysql
  become: true

- name: Adds Python MySQL support on Debian/Ubuntu
  apt: pkg="python-mysqldb" state=present
  become: true
  when: ansible_os_family == 'Debian'

- name: create a new user
  become: true
  mysql_user:
    name: wp_user
    password: erty
    priv: '*.*:ALL,GRANT'
    state: present
    login_user: root
    host: '%'

- mysql_db:
    name: wordpress
    state: present
    login_user: wp_user
    login_password: "erty"

- name: Changement sur iplocal
  become: true
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "^bind-address(.*)"
    line: "bind-address = {{ ansible_default_ipv4.address }}"
    backrefs: yes
  when: "'bdd1' in inventory_hostname"

- name: Changement sur iplocal
  become: true
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "^bind-address(.*)"
    line: "bind-address = {{ ansible_default_ipv4.address }}"
    backrefs: yes
  when: "'bdd2' in inventory_hostname"

- name: Restart Mysql
  become: true
  service: 
    name: mysql
    state: restarted